export const AGREGAR_PRODUCTO = '[PRODUCT] AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = '[PRODUCT] AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = '[PRODUCT] AGREGAR_PRODUCTO_ERROR';

export const DESCARGA_PRODUCTO = '[PRODUCT] DESCARGA_PRODUCTO';
export const DESCARGA_PRODUCTO_EXITO = '[PRODUCT] DESCARGA_PRODUCTO_EXITO';
export const DESCARGA_PRODUCTO_ERROR = '[PRODUCT] DESCARGA_PRODUCTO_ERROR';

export const ELIMINAR_PRODUCTO = '[PRODUCT] ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_EXITO = '[PRODUCT] ELIMINAR_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = '[PRODUCT] ELIMINAR_PRODUCTO_ERROR';

export const EDITAR_PRODUCTO = '[PRODUCT] EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = '[PRODUCT] EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = '[PRODUCT] EDITAR_PRODUCTO_ERROR';
